apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: network-debugger
spec:
  type: LoadBalancer
  selector:
    app: echo-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
